# -*- coding: utf-8 -*-
"""Bias_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsTtCw-nwWRBBOKHmVZOgne_tsoRluTe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

# Load the winning model and prepare the audit dataframe
winning_model = joblib.load('models/random_forest_model.pkl')

# Re-align geography
test_indices = y_test.index
audit_df = customer_df.loc[test_indices].copy()

# Add Predictions and Actuals
audit_df['true_val'] = np.expm1(y_test)
audit_df['pred_val'] = np.expm1(winning_model.predict(X_test))
audit_df['abs_error'] = abs(audit_df['true_val'] - audit_df['pred_val'])

if 'customer_state' not in audit_df.columns:
    state_map = df[['customer_unique_id', 'customer_state']].drop_duplicates()
    audit_df = audit_df.merge(state_map, on='customer_unique_id', how='left')

# Calculate Mean Absolute Error (MAE) by State
state_bias = audit_df.groupby('customer_state')['abs_error'].mean().sort_values()

# Visualize the "Bias Map"
plt.figure(figsize=(12, 6))
state_bias.plot(kind='bar', color='salmon')
plt.axhline(y=state_bias.mean(), color='blue', linestyle='--', label='Average Error')
plt.title('Fairness Audit: Model Prediction Error (MAE) by State')
plt.ylabel('Average Error in Dollars ($)')
plt.xlabel('Territory (State)')
plt.legend()
plt.tight_layout()
plt.show()

print(f"✅ Audit complete. Average MAE across all territories: ${state_bias.mean():.2f}")