# -*- coding: utf-8 -*-
"""Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T47ZhYeHcMp3xU5JgtNhUh5WGvhxWZIi
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.cluster import KMeans
import os
import joblib

#Prepare Training and Test Sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

#Experiment with Models
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "XGBoost": XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
}

results = []

print("🚀 Starting Model Competition...")
for name, model in models.items():
    # Train
    model.fit(X_train, y_train)

    # Predict
    preds = model.predict(X_test)

    # Evaluate
    rmse = np.sqrt(mean_squared_error(np.expm1(y_test), np.expm1(preds)))
    mae = mean_absolute_error(np.expm1(y_test), np.expm1(preds))
    r2 = r2_score(y_test, preds)

    results.append({"Model": name, "RMSE": rmse, "MAE": mae, "R2": r2})

    # Save Artifacts
    if not os.path.exists('models'):
        os.makedirs('models')
    joblib.dump(model, f'models/{name.replace(" ", "_").lower()}_model.pkl')

# Display Comparison Table
comparison_df = pd.DataFrame(results)
print("\n📊 Model Comparison Table:")
print(comparison_df.to_string(index=False))

# Unsupervised Clustering (Requirement: K-Means)
# We use 3 clusters as a baseline for Territory segments
print("\n📍 Running Territory Clustering...")
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10).fit(X_scaled)
customer_df['territory_cluster'] = kmeans.labels_

# Save the cluster model
joblib.dump(kmeans, 'models/territory_clusters.pkl')
print("✅ Clustering complete. Models saved in 'models/' folder.")

import matplotlib.pyplot as plt

# Use the PCA coordinates we calculated
plt.figure(figsize=(10, 7))

# Create the scatter plot using PCA components
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1],
            c=customer_df['territory_cluster'],
            cmap='viridis', alpha=0.6)

# Add labels and legend
plt.title('Sales Territory Clusters (PCA Projection)')
plt.xlabel('Principal Component 1 (Friction/Geography)')
plt.ylabel('Principal Component 2 (Secondary Variance)')
plt.colorbar(scatter, label='Cluster ID')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# Print Cluster Statistics (The "Business" View)
cluster_stats = customer_df.groupby('territory_cluster').agg({
    'total_value': ['mean', 'count'],
    'logistics_friction': 'mean'
}).round(2)

print("\n📊 Cluster Characteristic Summary:")
print(cluster_stats)