# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLxM9uSqn3IVxYydShsDfeb5ekRYpJ6z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestRegressor
import shap
import os

# Import Data
folder_path = '../data/'
print("🔄 Loading files from sample_data...")

try:
    customers = pd.read_csv(os.path.join(folder_path, 'olist_customers_dataset.csv'))
    orders = pd.read_csv(os.path.join(folder_path, 'olist_orders_dataset.csv'))
    items = pd.read_csv(os.path.join(folder_path, 'olist_order_items_dataset.csv'))
    products = pd.read_csv(os.path.join(folder_path, 'olist_products_dataset.csv'))
    print("✅ Data imported successfully!")
except FileNotFoundError as e:
    print(f"❌ Error: {e}")
    print("Please ensure the CSV files are inside the 'data' folder in Github.")

# Merge and Clean Data
# Requirement: Handle nulls, duplicates, and outliers
df = pd.merge(items, orders, on='order_id')
df = pd.merge(df, customers, on='customer_id')
df = pd.merge(df, products, on='product_id')

# Clean: Drop missing delivery dates and remove duplicates
df = df.dropna(subset=['order_delivered_customer_date']).drop_duplicates()

# Clean: Outlier Capping (99th percentile)
df['price'] = df['price'].clip(upper=df['price'].quantile(0.99))
df['freight_value'] = df['freight_value'].clip(upper=df['freight_value'].quantile(0.99))

# Feature Engineering
# Requirement: Domain-derived, Scaling, Encoding
df['total_value'] = df['price'] + df['freight_value']
df['logistics_friction'] = df['freight_value'] / df['price']

# Encode Geography
le = LabelEncoder()
df['state_encoded'] = le.fit_transform(df['customer_state'])

# Aggregate to unique customer level (for CLV prediction)
customer_df = df.groupby('customer_unique_id').agg({
    'total_value': 'sum',
    'logistics_friction': 'mean',
    'state_encoded': 'first'
}).reset_index()

# Scale features and log-transform the target
scaler = StandardScaler()
X = customer_df[['logistics_friction', 'state_encoded']]
y = np.log1p(customer_df['total_value'])
X_scaled = scaler.fit_transform(X)

# PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
print(f"✅ PCA Variance Ratio: {pca.explained_variance_ratio_}")

# SHAP
# Requirement: Feature Importance & Explainability
print("🧠 Training explainer model (this may take a moment)...")
model = RandomForestRegressor(n_estimators=30, random_state=42)
model.fit(X_scaled, y)

# Summary Plot for top 500 samples
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_scaled[:500])
shap.summary_plot(shap_values, X_scaled[:500], feature_names=['Logistics Friction', 'State (Geography)'])